### ISSUE TITLE
Couple of Functions are broken

### ISSUE THREAD

**Issue by OmniiOMEGA** [boivinx7/Teamviewer-PS-Module#1]
**Describe the bug**
When you go to use functions like **Unshare-TVGroup** it breaks and says Invoke-RestMethod : :"Unexpected character encountered while parsing value: {. Path 'Users', line 3, position 19.

Overview of other functions that are broken too:
**Share TVGroup
Create-TVUser**

**To Reproduce**
1. First run Set-TVToken -UserToken "TOKEN HERE"
2. Then run Unshare-TVGroup -GroupID g100734968 -UserID u118562496
3. Scroll down to see error

**Expected behavior**
I should see UserID removed from the GroupID g100734968

**Screenshots**
![powershell_ise_7r1jtLXUnn](https://user-images.githubusercontent.com/43362357/61191796-f2543200-a6e0-11e9-9dc5-413648255486.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, 1809
 - Browser: Chrome
 - Version: 75.0.3770.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 11.3.1
 - Browser Chrome
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by boivinx7** [comment]
Will be looking at this next week

**Comment by boivinx7** [comment]
unshare is fixed

**Comment by boivinx7** [comment]
Create-TV User now Renamed Add-TVUser should be now working.
Im not a 100% since I dont have any user to add. But it's not crashing anymore.
