### ISSUE TITLE
Create New Function Delete-TVUser

### ISSUE THREAD

**Issue by OmniiOMEGA** [boivinx7/Teamviewer-PS-Module#2]
**Is your feature request related to a problem? Please describe.**
Related to Create-TVUser

**Describe the solution you'd like**
A new function to do the opposite of Create-TVUser and that is to delete a TVUser.

**Describe alternatives you've considered**
Tried editing the script but still learning 💯 

**Additional context**
N/A

**Comment by boivinx7** [comment]
Will be adding this next week

**Comment by boivinx7** [comment]
Pretty Much Done, But no Output,
Will Try to get an output.
Also it shoot an error if user does not exist, will add a test if exist.

P.S. add to Change a bunch of function verbs to get rid of 
WARNING: The names of some imported commands from the module 'TeamViewerPSModules' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

**Comment by OmniiOMEGA** [comment]
Thanks boivinx7
Can't wait to test it :D

**Comment by boivinx7** [comment]
Finally Done and working, will be in next update on Github and PS Gallery
